[versions]
lavaplayer = "2.2.2"
lavaplayer-youtube-source = "641e49b2c6ab03c2ab63f732a36aa3a531fe7170-SNAPSHOT"

[libraries]
lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "lavaplayer-youtube-source" }