[versions]
lavaplayer = "2.2.3"
lavaplayer-youtube-source = "2f7a4d4bcb7fac0ff21c6fe19469ced558df33ad-SNAPSHOT"

[libraries]
lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "lavaplayer-youtube-source" }