name: lavaplayer-lib CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build lavaplayer-lib
        run: ./gradlew build
      - name: Upload lavaplayer-lib
        uses: actions/upload-artifact@v4
        with:
          name: "lavaplayer-lib"
          path: "build/libs/"